"""Generate capture shims and turn a capture log into manifests.

``weaver capture shim --tool cc=/usr/bin/gcc`` writes an executable ``cc``
shim that runs the wrapper around the real tool.  Build with the shim (for
example ``make CC=$PWD/.weaver/capture/shims/cc``) from a *clean* configured
build: an incremental build can miss unchanged files.  ``weaver capture
finalize`` then writes a compilation database (one entry per source file and
command), a link manifest and a tool manifest.
"""

from __future__ import annotations

import os
import shlex
import stat
import sys
from pathlib import Path
from typing import Any

import weaver
from weaver.capture.toolid import identify, resolve_executable
from weaver.errors import WeaverError
from weaver.toolchain.options import parse_driver_args
from weaver.util import read_jsonl, write_json


def make_shim(shim_dir: Path, name: str, real: str, log: Path, role: str = "compiler") -> Path:
    real_path = resolve_executable(real)
    if real_path is None:
        raise WeaverError(f"cannot find executable {real!r}")
    real_path = os.path.abspath(real_path)
    shim_dir.mkdir(parents=True, exist_ok=True)
    pkg_parent = str(Path(weaver.__file__).resolve().parent.parent)
    shim = shim_dir / name
    shim.write_text(
        "#!/bin/sh\n"
        "# Generated by weaver capture: records the invocation, then runs the real tool.\n"
        f"PYTHONPATH={shlex.quote(pkg_parent)}${{PYTHONPATH:+:$PYTHONPATH}} "
        f"exec {shlex.quote(sys.executable)} -m weaver.capture.wrapper "
        f"--real {shlex.quote(real_path)} --log {shlex.quote(str(log))} --role {shlex.quote(role)} "
        '-- "$@"\n'
    )
    shim.chmod(shim.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return shim


def finalize(log: Path, out_dir: Path) -> dict[str, Any]:
    """Convert a capture log into compile_commands.json, links.json and tools.json."""
    records = read_jsonl(log)
    if not records:
        raise WeaverError(f"capture log {log} is empty; did the build use the shims?")
    compdb: list[dict[str, Any]] = []
    links: list[dict[str, Any]] = []
    other: list[dict[str, Any]] = []
    failed: list[dict[str, Any]] = []
    tools: dict[str, Any] = {}
    seen: set[tuple[str, str, str]] = set()

    for rec in records:
        argv = rec["expanded"]
        tool = rec["tool_realpath"]
        if tool not in tools:
            tools[tool] = identify(tool).to_json()
        if rec.get("returncode", 0) != 0:
            failed.append({"cwd": rec["cwd"], "argv": rec["argv"], "returncode": rec["returncode"]})
            continue
        pa = parse_driver_args(argv)
        if pa.action in ("-E",) or (pa.has_dep_flags and pa.action is None and not pa.output and pa.sources):
            other.append({"kind": "preprocess-or-deps", "cwd": rec["cwd"], "argv": rec["argv"]})
            continue
        for src, pos in zip(pa.sources, pa.source_positions):
            # One entry per source: drop the *other* sources from the argument list.
            others = {p for p in pa.source_positions if p != pos}
            args = [a for j, a in enumerate(rec["argv"]) if j not in others] if len(pa.sources) > 1 else rec["argv"]
            key = (rec["cwd"], src, " ".join(args))
            if key in seen:
                continue
            seen.add(key)
            entry: dict[str, Any] = {"directory": rec["cwd"], "file": src, "arguments": args}
            if pa.output and pa.action in ("-c", "-S") and len(pa.sources) == 1:
                entry["output"] = pa.output
            compdb.append(entry)
        if pa.asm_sources:
            other.append({"kind": "assembly", "cwd": rec["cwd"], "argv": rec["argv"], "inputs": pa.asm_sources})
        if pa.action is None and (pa.other_inputs or pa.sources):
            links.append(
                {
                    "cwd": rec["cwd"],
                    "argv": rec["argv"],
                    "inputs": pa.other_inputs,
                    "compiled_sources": pa.sources,
                    "output": pa.output or "a.out",
                    "tool": tool,
                    "env": rec.get("env", {}),
                }
            )

    out_dir.mkdir(parents=True, exist_ok=True)
    write_json(out_dir / "compile_commands.json", compdb)
    write_json(out_dir / "links.json", links)
    write_json(out_dir / "tools.json", tools)
    write_json(out_dir / "other-invocations.json", {"other": other, "failed": failed})
    return {
        "compile_entries": len(compdb),
        "links": len(links),
        "tools": list(tools),
        "failed_invocations": len(failed),
        "other_invocations": len(other),
        "out_dir": str(out_dir),
    }
